/* For global timestamp api */
export const GLOBAL_TIMESTAMP_API_SUCCESS = 'GLOBAL_TIMESTAMP_API_SUCCESS';
export const GLOBAL_TIMESTAMP_API_FAILURE = 'GLOBAL_TIMESTAMP_API_FAILURE';
export const GLOBAL_TIMESTAMP_API_PROGRESS = 'GLOBAL_TIMESTAMP_API_PROGRESS';
export const CLEAR_GLOBAL_TIMESTAMP_API_DATA =
  'CLEAR_GLOBAL_TIMESTAMP_API_DATA';

export const SET_TIMESTAMP = 'SET_TIMESTAMP';

/* For global json api */
export const GLOBAL_CONFIG_API_SUCCESS = 'GLOBAL_CONFIG_API_SUCCESS';
export const GLOBAL_CONFIG_API_FAILURE = 'GLOBAL_CONFIG_API_FAILURE';
export const GLOBAL_CONFIG_API_PROGRESS = 'GLOBAL_CONFIG_API_PROGRESS';
export const CLEAR_GLOBAL_CONFIG_API_DATA = 'CLEAR_GLOBAL_CONFIG_API_DATA';

/* For login json api */
export const LOGIN_CONFIG_API_SUCCESS = 'LOGIN_CONFIG_API_SUCCESS';
export const LOGIN_CONFIG_API_FAILURE = 'LOGIN_CONFIG_API_FAILURE';
export const LOGIN_CONFIG_API_PROGRESS = 'LOGIN_CONFIG_API_PROGRESS';
export const CLEAR_LOGIN_CONFIG_API_DATA = 'CLEAR_LOGIN_CONFIG_API_DATA';

/* For countries list json api */
export const COUNTRIES_LIST_API_SUCCESS = 'COUNTRIES_LIST_API_SUCCESS';
export const COUNTRIES_LIST_API_FAILURE = 'COUNTRIES_LIST_API_FAILURE';
export const COUNTRIES_LIST_API_PROGRESS = 'COUNTRIES_LIST_API_PROGRESS';
export const CLEAR_COUNTRIES_LIST_API_DATA = 'CLEAR_COUNTRIES_LIST_API_DATA';

/* For fetching data of selected language */
export const FETCH_TRANSLATION_SUCCESS = 'FETCH_TRANSLATION_SUCCESS';
export const FETCH_TRANSLATION_FAILURE = 'FETCH_TRANSLATION_FAILURE';
export const FETCH_TRANSLATION_PROGRESS = 'FETCH_TRANSLATION_PROGRESS';
export const CLEAR_TRANSLATION_API_DATA = 'CLEAR_TRANSLATION_API_DATA';

/* For setting the country */
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
/* For setting the language */
export const SET_SELECTED_COUNTRY_LANGUAGE = 'SET_SELECTED_COUNTRY_LANGUAGE';

/* For storing the localization traslation instance for selected language */
export const SET_APP_TRANSLATION_DATA = 'SET_APP_TRANSLATION_DATA';

/* For storing the localization traslation instance for login data for selected country */
export const SET_LOGIN_TRANSLATION_DATA = 'SET_LOGIN_TRANSLATION_DATA';

/* For clearing all the json files */
export const CLEAR_ALL_TRANSLATION_DATA = 'CLEAR_ALL_TRANSLATION_DATA';