export const GLOBAL_CONFIG_API_SUCCESS = 'GLOBAL_CONFIG_API_SUCCESS';
export const GLOBAL_CONFIG_API_FAILURE = 'GLOBAL_CONFIG_API_FAILURE';
export const GLOBAL_CONFIG_API_PROGRESS = 'GLOBAL_CONFIG_API_PROGRESS';
export const CLEAR_GLOBAL_CONFIG_API_DATA = 'CLEAR_GLOBAL_CONFIG_API_DATA';

export const LOGIN_CONFIG_API_SUCCESS = 'LOGIN_CONFIG_API_SUCCESS';
export const LOGIN_CONFIG_API_FAILURE = 'LOGIN_CONFIG_API_FAILURE';
export const LOGIN_CONFIG_API_PROGRESS = 'LOGIN_CONFIG_API_PROGRESS';
export const CLEAR_LOGIN_CONFIG_API_DATA = 'CLEAR_LOGIN_CONFIG_API_DATA';

export const COUNTRIES_LIST_API_SUCCESS = 'COUNTRIES_LIST_API_SUCCESS';
export const COUNTRIES_LIST_API_FAILURE = 'COUNTRIES_LIST_API_FAILURE';
export const COUNTRIES_LIST_API_PROGRESS = 'COUNTRIES_LIST_API_PROGRESS';
export const CLEAR_COUNTRIES_LIST_API_DATA = 'CLEAR_COUNTRIES_LIST_API_DATA';

export const FETCH_TRANSLATION_SUCCESS = 'FETCH_TRANSLATION_SUCCESS';
export const FETCH_TRANSLATION_FAILURE = 'FETCH_TRANSLATION_FAILURE';
export const FETCH_TRANSLATION_PROGRESS = 'FETCH_TRANSLATION_PROGRESS';
export const CLEAR_TRANSLATION_API_DATA = 'CLEAR_TRANSLATION_API_DATA';

export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_COUNTRY_LANGUAGE = 'SET_SELECTED_COUNTRY_LANGUAGE';

export const SET_APP_TRANSLATION_DATA = 'SET_APP_TRANSLATION_DATA';
export const SET_LOGIN_TRANSLATION_DATA = 'SET_LOGIN_TRANSLATION_DATA';
